openapi: 3.0.0
info:
  title: Drinks Service API
  description: API for retrieving drinks and their prices.
  version: 1.0.0
paths:
  /drinks:
    get:
      summary: Get drinks and their prices
      responses:
        '200':
          description: A list of drinks with their prices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "Coca Cola"
                    price:
                      type: number
                      format: float
                      example: 1.99
