openapi: 3.0.0
info:
  title: Room Types Service API
  description: API for retrieving room types.
  version: 1.0.0
paths:
  /room_types:
    get:
      summary: Get room types
      responses:
        '200':
          description: A list of room types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      example: "Deluxe"
                    description:
                      type: string
                      example: "A deluxe room with sea view"
